// 50 curated interior design styles with popularity scores (0-100) and categories.
export const INTERIOR_STYLES = [
  { name: "Minimalist", category: "Modern", popularity: 98, description: "Clean lines, neutral palette, less is more." },
  { name: "Scandinavian", category: "Modern", popularity: 95, description: "Light woods, white walls, cozy functionality." },
  { name: "Japandi", category: "Modern", popularity: 94, description: "Japanese restraint meets Scandinavian warmth." },
  { name: "Soft Minimal", category: "Modern", popularity: 92, description: "Muted tones, rounded forms, gentle calm." },
  { name: "Warm Minimal", category: "Natural", popularity: 91, description: "Minimal structure with warm, tactile materials." },
  { name: "Modern Organic", category: "Natural", popularity: 90, description: "Organic shapes, natural textures, modern bones." },
  { name: "Mid-Century Modern", category: "Retro", popularity: 89, description: "1950s silhouettes, tapered legs, teak tones." },
  { name: "Organic Modern", category: "Natural", popularity: 88, description: "Curved lines, stone and wood, earthy neutrals." },
  { name: "Industrial", category: "Urban", popularity: 87, description: "Exposed brick, steel, raw concrete." },
  { name: "Bohemian", category: "Eclectic", popularity: 86, description: "Layered textiles, plants, global accents." },
  { name: "Coastal", category: "Natural", popularity: 85, description: "Airy blues, whites, natural light, breezy." },
  { name: "Modern Farmhouse", category: "Rustic", popularity: 84, description: "Rustic charm with clean modern lines." },
  { name: "Contemporary", category: "Modern", popularity: 83, description: "Of-the-moment, current, ever-evolving." },
  { name: "Earthy", category: "Natural", popularity: 82, description: "Terracotta, clay, ochre, grounded tones." },
  { name: "Wabi-Sabi", category: "Natural", popularity: 81, description: "Imperfect, handmade, quietly beautiful." },
  { name: "Traditional", category: "Classic", popularity: 80, description: "Timeless symmetry, antiques, refinement." },
  { name: "Urban Modern", category: "Urban", popularity: 79, description: "Sleek city living, bold but livable." },
  { name: "Transitional", category: "Modern", popularity: 78, description: "Bridge between traditional and modern." },
  { name: "Rustic", category: "Rustic", popularity: 77, description: "Reclaimed wood, stone, rugged warmth." },
  { name: "Asian Zen", category: "Natural", popularity: 76, description: "Balance, harmony, uncluttered calm." },
  { name: "Art Deco", category: "Classic", popularity: 75, description: "1920s glamour, geometric luxury." },
  { name: "Maximalist", category: "Eclectic", popularity: 74, description: "More is more — bold patterns, rich color." },
  { name: "Monochrome", category: "Modern", popularity: 73, description: "Single palette, tonal depth, graphic." },
  { name: "French Country", category: "Rustic", popularity: 72, description: "Provencal elegance, soft pastels, wood." },
  { name: "Tropical Modern", category: "Natural", popularity: 71, description: "Lush greenery meets clean modern form." },
  { name: "Hollywood Regency", category: "Glam", popularity: 70, description: "High-gloss glamour, lacquer, brass." },
  { name: "Mediterranean", category: "Classic", popularity: 69, description: "Sun-washed stone, arches, terracotta." },
  { name: "Eclectic", category: "Eclectic", popularity: 68, description: "A curated mix of eras and origins." },
  { name: "Glam", category: "Glam", popularity: 67, description: "Velvet, marble, metallics, drama." },
  { name: "Desert Modern", category: "Natural", popularity: 66, description: "Sun-bleached tones, clean desert lines." },
  { name: "Southwestern", category: "Rustic", popularity: 65, description: "Earthy clay, woven textiles, desert warmth." },
  { name: "Cottagecore", category: "Rustic", popularity: 64, description: "Romantic rural, florals, vintage charm." },
  { name: "Shabby Chic", category: "Vintage", popularity: 63, description: "Distressed whites, soft florals, feminine." },
  { name: "Tropical", category: "Natural", popularity: 62, description: "Bold botanicals, rattan, vibrant greens." },
  { name: "Grandmillennial", category: "Classic", popularity: 61, description: "Chintz, skirts, nostalgic traditional." },
  { name: "Vintage", category: "Vintage", popularity: 60, description: "Curated antiques, aged patina, character." },
  { name: "Retro", category: "Retro", popularity: 59, description: "70s color, bold shapes, nostalgic fun." },
  { name: "Country", category: "Rustic", popularity: 58, description: "Cozy farmhouse, gingham, warm wood." },
  { name: "Moroccan", category: "Global", popularity: 57, description: "Mosaic, jewel tones, intricate pattern." },
  { name: "Art Nouveau", category: "Classic", popularity: 56, description: "Whiplash curves, botanical ornament." },
  { name: "Victorian", category: "Classic", popularity: 55, description: "Ornate, opulent, richly detailed." },
  { name: "Nautical", category: "Natural", popularity: 54, description: "Rope, navy, stripes, seaside crisp." },
  { name: "Bauhaus", category: "Modern", popularity: 53, description: "Form follows function, primary geometry." },
  { name: "Colonial", category: "Classic", popularity: 52, description: "Symmetrical, paneled, historically rooted." },
  { name: "Gothic", category: "Dark", popularity: 51, description: "Moody, dark, dramatic, ornate." },
  { name: "Preppy", category: "Classic", popularity: 50, description: "Crisp, tailored, classic-American bright." },
  { name: "Hellenic", category: "Classic", popularity: 49, description: "Whitewashed, blue-and-white, Cycladic." },
  { name: "Memphis", category: "Retro", popularity: 48, description: "80s postmodern, bold color, squiggles." },
  { name: "Brutalist", category: "Industrial", popularity: 47, description: "Heavy concrete, monolithic, raw." },
  { name: "Steampunk", category: "Industrial", popularity: 46, description: "Victorian machinery, brass, gears." },
];

export const STYLE_CATEGORIES = ["All", "Modern", "Natural", "Rustic", "Classic", "Retro", "Urban", "Eclectic", "Glam", "Vintage", "Global", "Dark", "Industrial"];